version: "3.2"
services:
  docker-cfssl:
    build:
      context: .
      dockerfile: Dockerfile
    image: mudpuppy/cfssl:latest
    container_name: docker-cfssl
    ports:
      - "8888:8888"
    volumes:
      - /opt/docker/cfssl/certs/ca.pem:/etc/cfssl/ca.pem
      - /opt/docker/cfssl/certs/ca-key.pem:/etc/cfssl/ca-key.pem
      - /opt/docker/cfssl/ca_config.json:/etc/cfssl/ca_config.json
      - /opt/docker/cfssl/db_config.json:/etc/cfssl/db_config.json
      - /opt/docker/cfssl/certs.db:/etc/cfssl/certs.db
      - /opt/docker/cfssl/multiroot-profile.ini:/etc/cfssl/multiroot-profile.ini
      - /opt/docker/cfssl/certs/api.pem:/etc/cfssl/api.pem
      - /opt/docker/cfssl/certs/api-key.pem:/etc/cfssl/api-key.pem

    command: -a 0.0.0.0:8888 -l default -roots /etc/cfssl/multiroot-profile.ini -tls-cert /etc/cfssl/api.pem -tls-key /etc/cfssl/api-key.pem